# Config file for automatic testing at travis-ci.org

language: python
python:
  - "3.6"

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt
  - pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: python -m unittest discover gcgc.tests
