site_name: "GCGC Documentation"
theme:
  name: "material"
  logo:
    icon: "bug_report"
  palette:
    primary: "dark blue"
    accent: "white"
  font:
    code: "PT Mono"
markdown_extensions:
  - codehilite
  - admonition
extra_css:
  - 'stylesheets/extra.css'
